services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-server
    restart: always
    ports:
      - "8888:8888" # HLS Web Player Port
      - "8554:8554" # RTSP Ingest Port
    
  backend:
    build: ./backend
    container_name: scte-backend
    restart: always
    ports:
      - "8000:8000" # API & UI Port
    volumes:
      - ./frontend:/app/frontend